version: "3.0"

services:
  elasticsearch:
    container_name: elasticsearch
    image: "elasticsearch:8.0.0"
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - elastic-net
    ports:
      - 9200:9200

  kibana:
    container_name: kibana
    image: "kibana:8.0.0"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - elastic-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

  elastic-init:
    container_name: elastic-init
    build: ./elastic-init
    links:
      - elasticsearch
    networks:
      - elastic-net
    depends_on:
      - elasticsearch

  chatapp:
    container_name: chatapp
    build: .
    networks:
      - elastic-net
    depends_on:
      - elastic-init
    ports:
      - "8000:8000"

networks:
  elastic-net:
    driver: bridge